
-- ADD COLUMNS: INVEMAIL_ADDR(VARCHAR2(50))  INV_PREFERRED_METHOD TO MSSQL.ACCOUNTSMASTER (VARCHAR2(10))

ALTER TABLE mssql.accountsmaster
ADD(INVEMAIL_ADDR VARCHAR2(50));

ALTER TABLE mssql.accountsmaster
ADD(INV_PREFERRED_METHOD VARCHAR2(10));