ALTER TABLE mssql.dts_arilines
ADD(WWLINE NUMBER(1));
ALTER TABLE mssql.dts_arilines
ADD(WIDTHES NUMBER(7,3));
ALTER TABLE mssql.dts_arilines
ADD(HEIGHTES NUMBER(7,3));
ALTER TABLE mssql.dts_arilines
ADD(L1_DESC VARCHAR2(500));
ALTER TABLE mssql.dts_arilines
ADD(L2_DESC VARCHAR2(500));
ALTER TABLE mssql.dts_arilines
ADD(L1_LINETYPEID NUMBER(5));
ALTER TABLE mssql.dts_arilines
ADD(L1_MUTYPE VARCHAR2(50));
ALTER TABLE mssql.dts_arilines
ADD(L3_MULLTYPE VARCHAR2(25));