
--ordermaster: invoicenumber
CREATE INDEX IDX_ORDERMASTER_INVOICENUMBER
ON ORDERMASTER (INVOICENUMBER);
 
--dts_arimaster: invoice_processed
CREATE INDEX IDX_INVOICEPROCESSED
ON DTS_ARIMASTER (INVOICE_PROCESSED);
 
--dts_arimaster: trim("custcode")
CREATE INDEX IDX_TRIMCUSTCODE
ON DTS_ARIMASTER (TRIM(CUSTCODE));